{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/approvalwebauthn(approvaldata:username:options:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"approvalWebAuthn"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"approvalData"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSAuthentication","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","kind":"typeIdentifier"},{"kind":"text","text":"."},{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions","text":"WebAuthnAuthenticationOptions","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"TSApprovalCompletion","preciseIdentifier":"s:19TSAuthenticationSDK20TSApprovalCompletiona","kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSApprovalCompletion"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]]},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(approvalData:username:options:completion:)","interfaceLanguage":"swift"},"metadata":{"title":"approvalWebAuthn(approvalData:username:options:completion:)","externalID":"s:19TSAuthenticationSDK0A0C16approvalWebAuthn0C4Data8username7options10completionySDyS2SG_SSSgAC0dE21AuthenticationOptionsVys6ResultOyAA0aL0CAA0A5ErrorOGcSgtF","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"approvalWebAuthn"},{"kind":"text","text":"("},{"text":"approvalData","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","text":"TSAuthentication"},{"kind":"text","text":"."},{"text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK20TSApprovalCompletiona","text":"TSApprovalCompletion"},{"kind":"text","text":"?)"}],"role":"symbol","modules":[{"name":"TSAuthenticationSDK"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics, in order to verify a user’s authorization for a specific action."},{"type":"text","text":" "},{"text":"If authentication is completed successfully, this function will return a callback containing a WebAuthnEncodedResult.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"title":"TSAuthentication","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAuthentication"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAuthentication","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","url":"\/documentation\/tsauthenticationsdk\/tsauthentication"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/approvalWebAuthn(approvalData:username:options:completion:)":{"abstract":[{"type":"text","text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics, in order to verify a user’s authorization for a specific action."},{"text":" ","type":"text"},{"text":"If authentication is completed successfully, this function will return a callback containing a WebAuthnEncodedResult.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"approvalWebAuthn","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"approvalData"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","text":"TSAuthentication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","text":"WebAuthnAuthenticationOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"TSApprovalCompletion","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK20TSApprovalCompletiona"},{"kind":"text","text":"?)"}],"title":"approvalWebAuthn(approvalData:username:options:completion:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(approvalData:username:options:completion:)","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/approvalwebauthn(approvaldata:username:options:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/WebAuthnAuthenticationOptions":{"title":"TSAuthentication.WebAuthnAuthenticationOptions","kind":"symbol","navigatorTitle":[{"text":"WebAuthnAuthenticationOptions","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"WebAuthnAuthenticationOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for WebAuthn authentication."}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/webauthnauthenticationoptions"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSApprovalCompletion":{"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsapprovalcompletion","title":"TSApprovalCompletion","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSApprovalCompletion"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSApprovalCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSApprovalCompletion"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","op":"replace","value":"TSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","value":[{"text":"TSAuthentication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/navigatorTitle","value":[{"text":"TSAuthentication","kind":"identifier"}]}]}]}