{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticatePinCode"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"TSPinCodeAuthenticationResult","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSPinCodeAuthenticationResult","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeAuthenticationResultC"}]}]},{"kind":"parameters","parameters":[{"name":"username","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s identifier."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The entered PIN string."}]}],"name":"pinCode"},{"name":"challenge","content":[{"inlineContent":[{"type":"text","text":"The server‐provided challenge to prove possession of the PIN key."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"TSPinCodeAuthenticationResult","type":"codeVoice"},{"text":" on success.","type":"text"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"style":"note","type":"aside","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TSAuthenticationError"},{"text":" from the controller.","type":"text"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Async variant that actually performs the PIN authentication.","type":"text"}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"authenticatePinCode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pinCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"TSPinCodeAuthenticationResult","preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeAuthenticationResultC","kind":"typeIdentifier"}],"title":"authenticatePinCode(username:pinCode:challenge:)","externalID":"s:19TSAuthenticationSDK0A0C19authenticatePinCode8username03pinE09challengeAA05TSPinE20AuthenticationResultCSS_S2StYaKF","modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatepincode(username:pincode:challenge:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticatePinCode(username:pinCode:challenge:)":{"title":"authenticatePinCode(username:pinCode:challenge:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticatePinCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"TSPinCodeAuthenticationResult","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeAuthenticationResultC"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatepincode(username:pincode:challenge:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:)","abstract":[{"type":"text","text":"Async variant that actually performs the PIN authentication."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","role":"collection","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSPinCodeAuthenticationResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSPinCodeAuthenticationResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSPinCodeAuthenticationResult","url":"\/documentation\/tsauthenticationsdk\/tspincodeauthenticationresult","abstract":[],"title":"TSPinCodeAuthenticationResult","navigatorTitle":[{"kind":"identifier","text":"TSPinCodeAuthenticationResult"}],"type":"topic","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"title":"TSAuthentication","abstract":[],"navigatorTitle":[{"text":"TSAuthentication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAuthentication","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"value":[{"kind":"identifier","text":"TSAuthentication"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/navigatorTitle","value":[{"text":"TSAuthentication","kind":"identifier"}]}]}]}