{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration","text":"TSConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/initialize(baseurl:clientid:configuration:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:configuration:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a new WebAuthn SDK instance with your client context."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration"},{"kind":"text","text":"?)"}],"title":"initialize(baseUrl:clientId:configuration:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:19TSAuthenticationSDK0A0C10initialize7baseUrl8clientId13configurationySS_SSAA15TSConfigurationCSgtF","modules":[{"name":"TSAuthenticationSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"role":"symbol","title":"TSAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthentication"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSAuthentication"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/initialize(baseUrl:clientId:configuration:)":{"role":"symbol","title":"initialize(baseUrl:clientId:configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSConfiguration","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates a new WebAuthn SDK instance with your client context."}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/initialize(baseurl:clientid:configuration:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSConfiguration":{"role":"symbol","title":"TSConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSConfiguration"}],"url":"\/documentation\/tsauthenticationsdk\/tsconfiguration"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","value":[{"kind":"identifier","text":"TSAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/title","value":"TSConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/fragments","value":[{"kind":"identifier","text":"TSConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}