{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Unregister user’s Pin Code authenticator.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/unregisterPinCode(username:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:19TSAuthenticationSDK0A0C17unregisterPinCode8usernameAA05TSPinE20UnregistrationResultCSS_tYaKF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterPinCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeUnregistrationResultC","text":"TSPinCodeUnregistrationResult","kind":"typeIdentifier"}],"roleHeading":"Instance Method","modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol","title":"unregisterPinCode(username:)","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterPinCode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeUnregistrationResultC","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSPinCodeUnregistrationResult","text":"TSPinCodeUnregistrationResult","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"username","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s identifier."}]}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TSPinCodeUnregistrationResult"},{"text":" on success.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":""},{"code":"TSAuthenticationError","type":"codeVoice"},{"text":" from the controller.","type":"text"}],"type":"paragraph"}],"name":"Throws","type":"aside"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/unregisterpincode(username:)"]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"abstract":[],"title":"TSAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSAuthentication"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAuthentication"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/unregisterPinCode(username:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/unregisterPinCode(username:)","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/unregisterpincode(username:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterPinCode"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeUnregistrationResultC","kind":"typeIdentifier","text":"TSPinCodeUnregistrationResult"}],"kind":"symbol","title":"unregisterPinCode(username:)","abstract":[{"text":"Unregister user’s Pin Code authenticator.","type":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSPinCodeUnregistrationResult":{"abstract":[],"navigatorTitle":[{"text":"TSPinCodeUnregistrationResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSPinCodeUnregistrationResult","url":"\/documentation\/tsauthenticationsdk\/tspincodeunregistrationresult","title":"TSPinCodeUnregistrationResult","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSPinCodeUnregistrationResult"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","op":"replace","value":"TSAuthentication"},{"value":[{"kind":"identifier","text":"TSAuthentication"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/navigatorTitle","value":[{"kind":"identifier","text":"TSAuthentication"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}