{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions"]]},"abstract":[{"text":"SDK will attempt to authenticate using a local passkey credentials stored on the device.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"preferLocalCredantials","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TSAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"},{"kind":"text","text":"."},{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions","text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication\/webauthnauthenticationoptions\/preferlocalcredantials"]}],"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions\/preferLocalCredantials","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Type Property","title":"preferLocalCredantials","externalID":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV22preferLocalCredantialsAEvpZ","modules":[{"name":"TSAuthenticationSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferLocalCredantials"},{"kind":"text","text":": "},{"text":"TSAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","text":"WebAuthnAuthenticationOptions"}],"role":"symbol"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/WebAuthnAuthenticationOptions/preferLocalCredantials":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions\/preferLocalCredantials","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/webauthnauthenticationoptions\/preferlocalcredantials","title":"preferLocalCredantials","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferLocalCredantials"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","text":"TSAuthentication"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV"}],"role":"symbol","abstract":[{"type":"text","text":"SDK will attempt to authenticate using a local passkey credentials stored on the device."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","url":"\/documentation\/tsauthenticationsdk","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","abstract":[],"title":"TSAuthenticationSDK","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSAuthentication","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication","title":"TSAuthentication","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSAuthentication"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/WebAuthnAuthenticationOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"WebAuthnAuthenticationOptions","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/webauthnauthenticationoptions","abstract":[{"type":"text","text":"Options for WebAuthn authentication."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"WebAuthnAuthenticationOptions","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions","title":"TSAuthentication.WebAuthnAuthenticationOptions","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","value":[{"kind":"identifier","text":"TSAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/navigatorTitle","value":[{"kind":"identifier","text":"TSAuthentication"}]}]}]}