{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions"],"title":"Structures","anchor":"Structures","generated":true},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/buildNumber","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/version"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalNativeBiometrics(username:challenge:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(_:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(approvalData:username:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateNativeBiometrics(username:challenge:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateWebAuthn(_:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateWebAuthn(username:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/generateTOTPCode(UUID:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/generateTOTPCodeWithChallenge(UUID:challenge:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/getDeviceInfo(_:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:domain:initOptions:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initializeSDK(configuration:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerNativeBiometrics(username:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerPinCode(username:pinCode:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerPinCode(username:pinCode:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerTOTP(URI:securityType:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerWebAuthn(_:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerWebAuthn(username:displayName:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWebauthnTransaction(_:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWebauthnTransaction(username:options:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWithDeviceKey(challenge:completion:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/unregistersNativeBiometrics(username:completion:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/shared"],"anchor":"Type-Properties","generated":true},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/isNativeBiometricsEnrolled()","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/isWebAuthnSupported()"],"title":"Type Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/TSLogConfigurable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/9TSCoreSDK17TSLogConfigurableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthentication"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAuthentication","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"TSAuthentication","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAuthentication"}],"roleHeading":"Class","externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","modules":[{"name":"TSAuthenticationSDK"}],"navigatorTitle":[{"text":"TSAuthentication","kind":"identifier"}],"role":"symbol","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"kind":"symbol","references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/unregistersNativeBiometrics(username:completion:)":{"title":"unregistersNativeBiometrics(username:completion:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/unregistersNativeBiometrics(username:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/unregistersnativebiometrics(username:completion:)","abstract":[{"text":"Unregister native biometrics entry for a given user.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregistersNativeBiometrics"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSNativeBiometricsUnregisterCompletion","preciseIdentifier":"s:19TSAuthenticationSDK38TSNativeBiometricsUnregisterCompletiona"},{"kind":"text","text":")"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/approvalNativeBiometrics(username:challenge:completion:)":{"kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/approvalnativebiometrics(username:challenge:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approvalNativeBiometrics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSNativeBiometricsApprovalCompletion","preciseIdentifier":"s:19TSAuthenticationSDK36TSNativeBiometricsApprovalCompletiona"},{"kind":"text","text":")"}],"title":"approvalNativeBiometrics(username:challenge:completion:)","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalNativeBiometrics(username:challenge:completion:)","abstract":[{"type":"text","text":"Approves a user transaction using native biometrics (Touch ID or Face ID)."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/signWithDeviceKey(challenge:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signWithDeviceKey"},{"text":"(","kind":"text"},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TSAuthenticationSDK25TSSignChallengeCompletiona","text":"TSSignChallengeCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWithDeviceKey(challenge:completion:)","kind":"symbol","type":"topic","title":"signWithDeviceKey(challenge:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/signwithdevicekey(challenge:completion:)","role":"symbol","abstract":[{"text":"Signs the ","type":"text"},{"type":"codeVoice","code":"challenge"},{"type":"text","text":" string with the device key."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/initialize(baseUrl:clientId:domain:initOptions:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"baseUrl","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"initOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TSAuthenticationSDK0A11InitOptionsV","kind":"typeIdentifier","text":"TSAuthenticationInitOptions"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Creates a new SDK instance with your client context.","type":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initialize(baseUrl:clientId:domain:initOptions:)","title":"initialize(baseUrl:clientId:domain:initOptions:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/initialize(baseurl:clientid:domain:initoptions:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/TSLogConfigurable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/tslogconfigurable-implementations","title":"TSLogConfigurable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/TSLogConfigurable-Implementations","kind":"article"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticatePinCode(username:pinCode:challenge:completion:)":{"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatepincode(username:pincode:challenge:completion:)","abstract":[{"text":"Authenticates a user’s PIN against a server‐provided challenge, calling the completion handler when done.","type":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:completion:)","kind":"symbol","type":"topic","title":"authenticatePinCode(username:pinCode:challenge:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatePinCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pinCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK33TSPinCodeAuthenticationCompletiona","text":"TSPinCodeAuthenticationCompletion"},{"text":")","kind":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/WebAuthnAuthenticationOptions":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/WebAuthnAuthenticationOptions","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/webauthnauthenticationoptions","kind":"symbol","abstract":[{"type":"text","text":"Options for WebAuthn authentication."}],"title":"TSAuthentication.WebAuthnAuthenticationOptions","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"WebAuthnAuthenticationOptions","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WebAuthnAuthenticationOptions"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/signWebauthnTransaction(_:options:completion:)":{"title":"signWebauthnTransaction(_:options:completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signWebauthnTransaction"},{"kind":"text","text":"("},{"text":"TSWebAuthnAuthenticationData","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK28TSWebAuthnAuthenticationDataV"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","text":"TSAuthentication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"WebAuthnAuthenticationOptions","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"TSAuthenticationCompletion","preciseIdentifier":"s:19TSAuthenticationSDK0A10Completiona","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWebauthnTransaction(_:options:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/signwebauthntransaction(_:options:completion:)","abstract":[{"type":"text","text":"Initiates a WebAuthn credential signing transaction, typically prompting the user for biometrics or a security key."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerPinCode(username:pinCode:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPinCode"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"TSPinCodeRegistrationResult","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK27TSPinCodeRegistrationResultC"}],"kind":"symbol","abstract":[{"type":"text","text":"Async variant that actually performs the PIN registration."}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerPinCode(username:pinCode:)","title":"registerPinCode(username:pinCode:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registerpincode(username:pincode:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticateWebAuthn(_:options:completion:)":{"abstract":[{"text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateWebAuthn(_:options:completion:)","type":"topic","kind":"symbol","title":"authenticateWebAuthn(_:options:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatewebauthn(_:options:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticateWebAuthn","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:19TSAuthenticationSDK28TSWebAuthnAuthenticationDataV","kind":"typeIdentifier","text":"TSWebAuthnAuthenticationData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"TSAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication"},{"text":".","kind":"text"},{"preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier","text":"WebAuthnAuthenticationOptions"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TSAuthenticationSDK0A10Completiona","kind":"typeIdentifier","text":"TSAuthenticationCompletion"},{"text":"?)","kind":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerTOTP(URI:securityType:completion:)":{"abstract":[{"text":"Registers a TOTP code generator.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerTOTP"},{"kind":"text","text":"("},{"text":"URI","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"securityType"},{"text":": ","kind":"text"},{"text":"TSTOTPSecurityType","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK18TSTOTPSecurityTypeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TSAuthenticationSDK28TSTOTPRegistrationCompletiona","kind":"typeIdentifier","text":"TSTOTPRegistrationCompletion"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"registerTOTP(URI:securityType:completion:)","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerTOTP(URI:securityType:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registertotp(uri:securitytype:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticatePinCode(username:pinCode:challenge:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticatePinCode(username:pinCode:challenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatePinCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:19TSAuthenticationSDK29TSPinCodeAuthenticationResultC","text":"TSPinCodeAuthenticationResult","kind":"typeIdentifier"}],"abstract":[{"text":"Async variant that actually performs the PIN authentication.","type":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatepincode(username:pincode:challenge:)","title":"authenticatePinCode(username:pinCode:challenge:)","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerPinCode(username:pinCode:completion:)":{"abstract":[{"type":"text","text":"Registers a new PIN code for the given user, calling the completion handler when done."}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registerpincode(username:pincode:completion:)","title":"registerPinCode(username:pinCode:completion:)","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerPinCode(username:pinCode:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerPinCode","kind":"identifier"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"pinCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSPinCodeRegistrationCompletion","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK31TSPinCodeRegistrationCompletiona"},{"kind":"text","text":")"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerNativeBiometrics(username:completion:)":{"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerNativeBiometrics(username:completion:)","role":"symbol","abstract":[{"text":"Registers native biometrics (Touch ID or Face ID) on the device for user authentication.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerNativeBiometrics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"username","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TSAuthenticationSDK40TSNativeBiometricsRegistrationCompletiona","text":"TSNativeBiometricsRegistrationCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"registerNativeBiometrics(username:completion:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registernativebiometrics(username:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/isNativeBiometricsEnrolled()":{"abstract":[{"type":"text","text":"Checks if the user has enrolled biometric authentication (Touch ID or Face ID) on their device."}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/isNativeBiometricsEnrolled()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isNativeBiometricsEnrolled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isNativeBiometricsEnrolled()","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/isnativebiometricsenrolled()","role":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/generateTOTPCode(UUID:completion:)":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"generateTOTPCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"UUID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TSAuthenticationSDK28TSTOTPGenerateCodeCompletiona","kind":"typeIdentifier","text":"TSTOTPGenerateCodeCompletion"},{"text":")","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/generatetotpcode(uuid:completion:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/generateTOTPCode(UUID:completion:)","title":"generateTOTPCode(UUID:completion:)","abstract":[{"text":"Generates a Time-based One-Time Password (TOTP) code.","type":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticateNativeBiometrics(username:challenge:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateNativeBiometrics(username:challenge:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticateNativeBiometrics"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK42TSNativeBiometricsAuthenticationCompletiona","text":"TSNativeBiometricsAuthenticationCompletion"},{"kind":"text","text":")"}],"title":"authenticateNativeBiometrics(username:challenge:completion:)","role":"symbol","abstract":[{"type":"text","text":"Authenticates a user using native biometrics (Touch ID or Face ID)."}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatenativebiometrics(username:challenge:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/version":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/version","abstract":[],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/version","title":"version","role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/isWebAuthnSupported()":{"title":"isWebAuthnSupported()","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/isWebAuthnSupported()","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isWebAuthnSupported"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/iswebauthnsupported()","abstract":[{"text":"Checks if the WebAuthn feature is supported on the current iOS version.","type":"text"}],"role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"title":"TSAuthenticationSDK","type":"topic","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/approvalWebAuthn(approvalData:username:options:completion:)":{"abstract":[{"type":"text","text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics, in order to verify a user’s authorization for a specific action."},{"type":"text","text":" "},{"type":"text","text":"If authentication is completed successfully, this function will return a callback containing a WebAuthnEncodedResult."},{"text":" ","type":"text"},{"text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service","type":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/approvalwebauthn(approvaldata:username:options:completion:)","title":"approvalWebAuthn(approvalData:username:options:completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"approvalWebAuthn","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"approvalData"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"username","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"TSAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication"},{"kind":"text","text":"."},{"text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSApprovalCompletion","preciseIdentifier":"s:19TSAuthenticationSDK20TSApprovalCompletiona"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(approvalData:username:options:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"navigatorTitle":[{"text":"TSAuthentication","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"TSAuthentication","role":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","url":"\/documentation\/tsauthenticationsdk\/tsauthentication","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSAuthentication","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/authenticateWebAuthn(username:options:completion:)":{"title":"authenticateWebAuthn(username:options:completion:)","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/authenticatewebauthn(username:options:completion:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/authenticateWebAuthn(username:options:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticateWebAuthn"},{"kind":"text","text":"("},{"text":"username","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","kind":"typeIdentifier","text":"TSAuthentication"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","text":"WebAuthnAuthenticationOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TSAuthenticationSDK0A10Completiona","text":"TSAuthenticationCompletion","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics."},{"text":" ","type":"text"},{"text":"If authentication is completed successfully, this function will return a callback containing a WebAuthnEncodedResult.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/signWebauthnTransaction(username:options:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"signWebauthnTransaction","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication"},{"text":".","kind":"text"},{"text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TSAuthenticationSDK0A10Completiona","text":"TSAuthenticationCompletion","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/signwebauthntransaction(username:options:completion:)","kind":"symbol","title":"signWebauthnTransaction(username:options:completion:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/signWebauthnTransaction(username:options:completion:)","role":"symbol","abstract":[{"text":"Invokes a WebAuthn credential signing transaction, including prompting the user for biometrics.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If transaction signing is completed successfully, this function will return a callback containing a WebAuthnEncodedResult."},{"type":"text","text":" "},{"type":"text","text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerWebAuthn(_:completion:)":{"title":"registerWebAuthn(_:completion:)","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registerwebauthn(_:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerWebAuthn","kind":"identifier"},{"kind":"text","text":"("},{"text":"TSWebAuthnRegistrationData","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK26TSWebAuthnRegistrationDataV"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSRegistrationCompletion","preciseIdentifier":"s:19TSAuthenticationSDK24TSRegistrationCompletiona"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Initiates the client-side WebAuthn credential registration process using parameters provided by the backend."}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerWebAuthn(_:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/initializeSDK(configuration:)":{"abstract":[{"type":"text","text":"Creates a new SDK instance with your client context."},{"text":" ","type":"text"},{"type":"text","text":"Credentials are configured from TransmitSecurity.plist file"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/initializesdk(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeSDK"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK0A13ConfigurationV","text":"TSAuthenticationConfiguration"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/initializeSDK(configuration:)","kind":"symbol","title":"initializeSDK(configuration:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/approvalWebAuthn(_:options:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"approvalWebAuthn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TSWebAuthnAuthenticationData","preciseIdentifier":"s:19TSAuthenticationSDK28TSWebAuthnAuthenticationDataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"TSAuthentication","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"WebAuthnAuthenticationOptions","preciseIdentifier":"s:19TSAuthenticationSDK0A0C29WebAuthnAuthenticationOptionsV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"TSApprovalCompletion","preciseIdentifier":"s:19TSAuthenticationSDK20TSApprovalCompletiona","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Invokes a WebAuthn credential authentication, including prompting the user for biometrics, in order to verify a user’s authorization for a specific action."},{"type":"text","text":" "},{"type":"text","text":"If authentication is completed successfully, this function will return a callback containing a WebAuthnEncodedResult."},{"text":" ","type":"text"},{"text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will commuincate with Transmit’s Service","type":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/approvalwebauthn(_:options:completion:)","role":"symbol","type":"topic","title":"approvalWebAuthn(_:options:completion:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/approvalWebAuthn(_:options:completion:)","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/9TSCoreSDK17TSLogConfigurableP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/9TSCoreSDK17TSLogConfigurableP","title":"TSCoreSDK.TSLogConfigurable","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/registerWebAuthn(username:displayName:completion:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/registerWebAuthn(username:displayName:completion:)","abstract":[{"text":"Invokes a WebAuthn credential registration, including prompting the user for biometrics.","type":"text"},{"text":" ","type":"text"},{"text":"Upon successful completion of the registration process, this function will return a callback containing a WebAuthnEncodedResult.","type":"text"},{"text":" ","type":"text"},{"text":"The WebAuthnEncodedResult should be used to make a completion request using your backend API which will communicate with Transmit’s Service","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerWebAuthn"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"username"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSRegistrationCompletion","kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK24TSRegistrationCompletiona"},{"kind":"text","text":"?)"}],"title":"registerWebAuthn(username:displayName:completion:)","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/registerwebauthn(username:displayname:completion:)","role":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/generateTOTPCodeWithChallenge(UUID:challenge:completion:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/generateTOTPCodeWithChallenge(UUID:challenge:completion:)","title":"generateTOTPCodeWithChallenge(UUID:challenge:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateTOTPCodeWithChallenge"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"UUID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TSAuthenticationSDK28TSTOTPGenerateCodeCompletiona","text":"TSTOTPGenerateCodeCompletion"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Generates a Time-based One-Time Password (TOTP) code.","type":"text"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/generatetotpcodewithchallenge(uuid:challenge:completion:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/shared":{"abstract":[],"title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"TSAuthentication","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSAuthentication","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/shared","type":"topic","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/shared"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/getDeviceInfo(_:)":{"role":"symbol","type":"topic","title":"getDeviceInfo(_:)","url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/getdeviceinfo(_:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/getDeviceInfo(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeviceInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DeviceInfoCompletion","preciseIdentifier":"s:19TSAuthenticationSDK20DeviceInfoCompletiona"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Retrieves device-specific information, such as public key and its associated ID, which are unique to the application installed on the device."}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication/buildNumber":{"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication\/buildNumber","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tsauthentication\/buildnumber","title":"buildNumber"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"TSAuthentication","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"TSAuthentication","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TSAuthentication"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthentication"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"value":[{"kind":"identifier","text":"TSAuthentication"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/navigatorTitle","value":[{"kind":"identifier","text":"TSAuthentication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}