{"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tsconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tsconfiguration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration\/init(domain:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration\/domain"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TSConfiguration"}],"modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol","externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSConfiguration"}],"title":"TSConfiguration","roleHeading":"Class","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"sections":[],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"url":"\/documentation\/tsauthenticationsdk","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","type":"topic","kind":"symbol","role":"collection"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","title":"Swift.Equatable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","title":"Swift.Hashable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSConfiguration/init(domain:)":{"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsconfiguration\/init(domain:)","kind":"symbol","abstract":[],"title":"init(domain:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"domain","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration\/init(domain:)","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"TSConfiguration"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration","role":"symbol","type":"topic","title":"TSConfiguration","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tsconfiguration","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSConfiguration/domain":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"domain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSConfiguration\/domain","role":"symbol","type":"topic","title":"domain","abstract":[{"type":"text","text":"An associated domain with the web credentials service type when making a registration or assertion request; otherwise, the request returns an error. See Supporting associated domains for more information."},{"type":"text","text":" "},{"type":"text","text":"(https:\/\/developer.apple.com\/documentation\/xcode\/supporting-associated-domains)"}],"url":"\/documentation\/tsauthenticationsdk\/tsconfiguration\/domain","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TSConfiguration"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"TSConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TSConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/title","value":"TSConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"TSConfiguration"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSConfiguration\/fragments"}]}]}