{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"title":"TSWebAuthnPubKeyCredParamsData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData","modules":[{"name":"TSAuthenticationSDK"}],"symbolKind":"class"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(from:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(type:alg:)"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/Encodable-Implementations"]}],"sections":[],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"type":"topic","abstract":[],"title":"TSWebAuthnPubKeyCredParamsData","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/Encodable-Implementations":{"kind":"article","title":"Encodable Implementations","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/encodable-implementations","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/Encodable-Implementations","role":"collectionGroup","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/init(type:alg:)":{"kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(type:alg:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"alg","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(type:alg:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(type:alg:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"title":"TSAuthenticationSDK","type":"topic","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/init(from:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(from:)","title":"init(from:)","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(from:)","role":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TSWebAuthnPubKeyCredParamsData","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TSWebAuthnPubKeyCredParamsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title"},{"value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}