{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnuserdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnuserdata"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnUserData","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/init(from:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/init(id:name:displayName:)"]},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/Encodable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"metadata":{"externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","navigatorTitle":[{"text":"TSWebAuthnUserData","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnUserData"}],"title":"TSWebAuthnUserData","symbolKind":"class","modules":[{"name":"TSAuthenticationSDK"}],"roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData":{"title":"TSWebAuthnUserData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnUserData"}],"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnUserData"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData","type":"topic","kind":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData/Encodable-Implementations":{"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata\/encodable-implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/Encodable-Implementations","title":"Encodable Implementations"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData/init(from:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata\/init(from:)","title":"init(from:)","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/init(from:)","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","kind":"symbol","title":"TSAuthenticationSDK","role":"collection","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData/init(id:name:displayName:)":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","title":"init(id:name:displayName:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData\/init(id:name:displayName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"displayName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata\/init(id:name:displayname:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","type":"unresolvable","title":"Swift.Decodable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"TSWebAuthnUserData","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"TSWebAuthnUserData","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TSWebAuthnUserData","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnUserData"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/title","value":"TSWebAuthnUserData"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnUserData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/navigatorTitle","value":[{"text":"TSWebAuthnUserData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}