{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"role":"symbol","title":"TSWebAuthnCredentialRequestOptionsData","roleHeading":"Class","externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData","modules":[{"name":"TSAuthenticationSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"]}],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(from:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/Encodable-Implementations":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/encodable-implementations","role":"collectionGroup","type":"topic","kind":"article","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","title":"Swift.Hashable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/init(from:)":{"role":"symbol","title":"init(from:)","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(from:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/init(from:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","title":"Swift.Equatable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","title":"Swift.Decodable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)":{"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"challenge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pubKeyCredParams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData","text":"TSWebAuthnPubKeyCredParamsData"},{"kind":"text","text":"]?, "},{"text":"attestation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"excludeCredentials"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"authenticatorSelection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData"},{"text":"?, ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","text":"TSWebAuthnUserData"},{"text":"?, ","kind":"text"},{"text":"rp","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSWebAuthnRPData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/init(challenge:pubkeycredparams:attestation:excludecredentials:authenticatorselection:timeout:user:rp:)","title":"init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","title":"Swift.Encodable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","title":"TSWebAuthnCredentialRequestOptionsData","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TSWebAuthnCredentialRequestOptionsData"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"TSWebAuthnCredentialRequestOptionsData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title","op":"replace"},{"op":"replace","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}]}]}]}