{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata"]},{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"modules":[{"name":"TSAuthenticationSDK"}],"roleHeading":"Class","role":"symbol","title":"TSWebAuthnAllowCredentialsData","externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(from:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(id:name:displayName:)"],"anchor":"Initializers","generated":true},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/Encodable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations","type":"topic","title":"Encodable Implementations","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/encodable-implementations","role":"collectionGroup","kind":"article"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/init(id:name:displayName:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(id:name:displayName:)","kind":"symbol","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/init(id:name:displayname:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"displayName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(id:name:displayName:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"abstract":[],"title":"TSWebAuthnAllowCredentialsData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"url":"\/documentation\/tsauthenticationsdk","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","title":"TSAuthenticationSDK","kind":"symbol","role":"collection","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/init(from:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(from:)","abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol","title":"init(from:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"TSWebAuthnAllowCredentialsData","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}]},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TSWebAuthnAllowCredentialsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title"},{"value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments"},{"value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle"}]}]}