{"sections":[],"metadata":{"role":"symbol","modules":[{"name":"TSAuthenticationSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"symbolKind":"class","roleHeading":"Class","title":"TSWebAuthnAuthenticatorSelectionData","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData"},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(authenticatorAttachment:requireResidentKey:userVerification:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(from:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/Encodable-Implementations"],"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata"]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/init(from:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"role":"symbol","title":"init(from:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(from:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(from:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"title":"TSWebAuthnAuthenticatorSelectionData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","role":"symbol","kind":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/Encodable-Implementations":{"title":"Encodable Implementations","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/encodable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/Encodable-Implementations","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/init(authenticatorAttachment:requireResidentKey:userVerification:)":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(authenticatorattachment:requireresidentkey:userverification:)","title":"init(authenticatorAttachment:requireResidentKey:userVerification:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"authenticatorAttachment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"requireResidentKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userVerification"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(authenticatorAttachment:requireResidentKey:userVerification:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TSWebAuthnAuthenticatorSelectionData"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}]},{"value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TSWebAuthnAuthenticatorSelectionData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title","op":"replace"},{"value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments","op":"replace"},{"value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}