{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnRPData","kind":"identifier"}],"externalID":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnRPData"}],"role":"symbol","modules":[{"name":"TSAuthenticationSDK"}],"symbolKind":"class","title":"TSWebAuthnRPData"},"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/init(from:)","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/init(id:name:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/Encodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnRPData"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnrpdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnrpdata"]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s28CustomDebugStringConvertibleP"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SH"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData":{"abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnRPData"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnRPData"}],"title":"TSWebAuthnRPData","kind":"symbol","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SQ"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s23CustomStringConvertibleP"},"doc://com.TransmitSecurity.TSAuthenticationSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/Se"},"doc://com.TransmitSecurity.TSAuthenticationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/s7CVarArgP"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData/Encodable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/encodable-implementations","kind":"article","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/Encodable-Implementations","title":"Encodable Implementations","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/SE"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData/init(from:)":{"type":"topic","abstract":[],"title":"init(from:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/init(from:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/init(from:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","title":"TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(pl)NSObject"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData/init(id:name:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/init(id:name:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/init(id:name:)","title":"init(id:name:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"TSWebAuthnRPData","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"TSWebAuthnRPData","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"TSWebAuthnRPData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"TSWebAuthnRPData","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/title","value":"TSWebAuthnRPData","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/fragments","op":"replace","value":[{"text":"TSWebAuthnRPData","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnRPData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}