{"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_dictionary"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_toDictionary(_:)"]}],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/encodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","metadata":{"modules":[{"name":"TSAuthenticationSDK"}],"title":"Encodable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"sections":[],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"kind":"symbol","type":"topic","title":"TSWebAuthnAllowCredentialsData","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/ts_dictionary":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_dictionary"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"role":"symbol","abstract":[],"title":"ts_dictionary","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_dictionary","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_dictionary"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","url":"\/documentation\/tsauthenticationsdk","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","abstract":[],"title":"TSAuthenticationSDK","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/ts_toDictionary(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation11JSONEncoderC","kind":"typeIdentifier","text":"JSONEncoder"},{"kind":"text","text":") -> ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"kind":"symbol","title":"ts_toDictionary(_:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_toDictionary(_:)","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_todictionary(_:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title","value":"TSWebAuthnAllowCredentialsData"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}