{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(from:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol","externalID":"s:19TSAuthenticationSDK30TSWebAuthnAllowCredentialsDataC4fromACs7Decoder_p_tKcfc","title":"init(from:)"},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData"]]},"sections":[],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"kind":"symbol","navigatorTitle":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"title":"TSWebAuthnAllowCredentialsData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/init(from:)":{"role":"symbol","title":"init(from:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/init(from:)","kind":"symbol","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title","op":"replace","value":"TSWebAuthnAllowCredentialsData"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}