{"metadata":{"role":"symbol","modules":[{"name":"TSAuthenticationSDK","relatedModules":["Swift"]}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"roleHeading":"Instance Property","symbolKind":"property","extendedModule":"Swift","title":"ts_dictionary","externalID":"s:SE9TSCoreSDKE13ts_dictionarySDySSypGSgvp::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Encodable.ts_dictionary"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_dictionary"},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_dictionary"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations"]]},"kind":"symbol","sections":[],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"abstract":[],"role":"symbol","kind":"symbol","title":"TSWebAuthnAllowCredentialsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"navigatorTitle":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/ts_dictionary":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_dictionary","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_dictionary","title":"ts_dictionary","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","title":"TSAuthenticationSDK","kind":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/Encodable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/encodable-implementations","type":"topic","kind":"article","abstract":[],"title":"Encodable Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"value":"TSWebAuthnAllowCredentialsData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments","value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle","value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}