{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ts_toDictionary","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"encoder"},{"text":": ","kind":"text"},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"kind":"text","text":" = JSONEncoder()) -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_todictionary(_:)"]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"TSAuthenticationSDK","relatedModules":["Swift"]}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"kind":"text","text":") -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"extendedModule":"Swift","externalID":"s:SE9TSCoreSDKE15ts_toDictionaryySDySSypGSg10Foundation11JSONEncoderCF::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData","symbolKind":"method","title":"ts_toDictionary(_:)"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_toDictionary(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Encodable.ts_toDictionary(_:)"},{"type":"text","text":"."}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/Encodable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/Encodable-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/encodable-implementations","title":"Encodable Implementations","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData/ts_toDictionary(_:)":{"title":"ts_toDictionary(_:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata\/ts_todictionary(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData\/ts_toDictionary(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ts_toDictionary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSONEncoder","preciseIdentifier":"s:10Foundation11JSONEncoderC","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","role":"symbol","navigatorTitle":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"title":"TSWebAuthnAllowCredentialsData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TSWebAuthnAllowCredentialsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title"},{"value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}]}]}]}