{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/ts_todictionary(_:)"]}],"kind":"symbol","metadata":{"modules":[{"relatedModules":["Swift"],"name":"TSAuthenticationSDK"}],"title":"ts_toDictionary(_:)","extendedModule":"Swift","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"symbolKind":"method","externalID":"s:SE9TSCoreSDKE15ts_toDictionaryySDySSypGSg10Foundation11JSONEncoderCF::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.ts_toDictionary(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_toDictionary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"encoder","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder"},{"text":" = JSONEncoder()) -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/Encodable-Implementations"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/ts_toDictionary(_:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData/ts_toDictionary(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"kind":"text","text":"("},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/ts_todictionary(_:)","role":"symbol","title":"ts_toDictionary(_:)","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/ts_toDictionary(_:)","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","kind":"symbol","title":"TSAuthenticationSDK","role":"collection","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData/Encodable-Implementations":{"kind":"article","title":"Encodable Implementations","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData\/Encodable-Implementations","url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata\/encodable-implementations","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnRPData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata","kind":"symbol","role":"symbol","title":"TSWebAuthnRPData","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData","type":"topic","navigatorTitle":[{"text":"TSWebAuthnRPData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TSWebAuthnRPData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnRPData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnRPData"}]}]}]}