{"sections":[],"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationResult","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsAuthenticationResult","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsRegistrationResult","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSRegistrationResult","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPGenerateCodeResult","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPRegistrationResult"],"title":"Classes"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSDeviceInfo"],"title":"Structures"},{"title":"Type Aliases","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/DeviceInfoCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSApprovalCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsAuthenticationCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsRegistrationCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSRegistrationCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPGenerateCodeCompletion","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPRegistrationCompletion"]},{"title":"Enumerations","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsError","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPError","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPSecurityType","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError"]}],"metadata":{"symbolKind":"module","role":"collection","modules":[{"name":"TSAuthenticationSDK"}],"roleHeading":"Framework","externalID":"TSAuthenticationSDK","title":"TSAuthenticationSDK"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/tsauthenticationsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tsauthenticationsdk"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Introduction","anchor":"Introduction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Authentication SDK is a client-side iOS SDK that allows you to easily integrate native authentication capabilities into your iOS application."}]}],"kind":"content"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationResult":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationResult","type":"topic","title":"TSAuthenticationResult","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationresult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAuthenticationResult"}],"navigatorTitle":[{"text":"TSAuthenticationResult","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSNativeBiometricsRegistrationCompletion":{"abstract":[],"kind":"symbol","title":"TSNativeBiometricsRegistrationCompletion","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TSNativeBiometricsRegistrationCompletion","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsRegistrationCompletion","navigatorTitle":[{"text":"TSNativeBiometricsRegistrationCompletion","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsnativebiometricsregistrationcompletion","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSRegistrationCompletion":{"navigatorTitle":[{"text":"TSRegistrationCompletion","kind":"identifier"}],"title":"TSRegistrationCompletion","url":"\/documentation\/tsauthenticationsdk\/tsregistrationcompletion","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSRegistrationCompletion","kind":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSRegistrationCompletion"}],"role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPRegistrationResult":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"TSTOTPRegistrationResult","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPRegistrationResult","url":"\/documentation\/tsauthenticationsdk\/tstotpregistrationresult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSTOTPRegistrationResult"}],"title":"TSTOTPRegistrationResult","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPError":{"url":"\/documentation\/tsauthenticationsdk\/tstotperror","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPError","abstract":[],"title":"TSTOTPError","navigatorTitle":[{"text":"TSTOTPError","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSTOTPError","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSNativeBiometricsAuthenticationResult":{"kind":"symbol","role":"symbol","abstract":[],"title":"TSNativeBiometricsAuthenticationResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSNativeBiometricsAuthenticationResult"}],"type":"topic","navigatorTitle":[{"text":"TSNativeBiometricsAuthenticationResult","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsnativebiometricsauthenticationresult","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsAuthenticationResult"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSApprovalCompletion":{"url":"\/documentation\/tsauthenticationsdk\/tsapprovalcompletion","kind":"symbol","title":"TSApprovalCompletion","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSApprovalCompletion","navigatorTitle":[{"text":"TSApprovalCompletion","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSApprovalCompletion","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationSDKVersionString":{"abstract":[{"text":"Project version string for TSAuthenticationSDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationsdkversionstring","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationSDKVersionString","role":"symbol","fragments":[{"kind":"identifier","text":"TSAuthenticationSDKVersionString"}],"title":"TSAuthenticationSDKVersionString","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSNativeBiometricsError":{"title":"TSNativeBiometricsError","url":"\/documentation\/tsauthenticationsdk\/tsnativebiometricserror","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"TSNativeBiometricsError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSNativeBiometricsError"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationSDKVersionNumber":{"type":"topic","title":"TSAuthenticationSDKVersionNumber","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationsdkversionnumber","abstract":[{"type":"text","text":"Project version number for TSAuthenticationSDK."}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationSDKVersionNumber","role":"symbol","fragments":[{"text":"TSAuthenticationSDKVersionNumber","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/DeviceInfoCompletion":{"navigatorTitle":[{"text":"DeviceInfoCompletion","kind":"identifier"}],"type":"topic","title":"DeviceInfoCompletion","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/deviceinfocompletion","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/DeviceInfoCompletion","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceInfoCompletion"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSNativeBiometricsRegistrationResult":{"navigatorTitle":[{"kind":"identifier","text":"TSNativeBiometricsRegistrationResult"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsRegistrationResult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSNativeBiometricsRegistrationResult"}],"title":"TSNativeBiometricsRegistrationResult","url":"\/documentation\/tsauthenticationsdk\/tsnativebiometricsregistrationresult"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthentication":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthentication"}],"role":"symbol","navigatorTitle":[{"text":"TSAuthentication","kind":"identifier"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tsauthentication","abstract":[],"title":"TSAuthentication","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSRegistrationResult":{"title":"TSRegistrationResult","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSRegistrationResult","url":"\/documentation\/tsauthenticationsdk\/tsregistrationresult","abstract":[],"navigatorTitle":[{"text":"TSRegistrationResult","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSRegistrationResult","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","abstract":[],"kind":"symbol","type":"topic","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPSecurityType":{"abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSTOTPSecurityType","kind":"identifier"}],"navigatorTitle":[{"text":"TSTOTPSecurityType","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPSecurityType","title":"TSTOTPSecurityType","url":"\/documentation\/tsauthenticationsdk\/tstotpsecuritytype","role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError":{"title":"TSAuthenticationError","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"TSAuthenticationError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TSAuthenticationError","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSNativeBiometricsAuthenticationCompletion":{"role":"symbol","kind":"symbol","type":"topic","title":"TSNativeBiometricsAuthenticationCompletion","url":"\/documentation\/tsauthenticationsdk\/tsnativebiometricsauthenticationcompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSNativeBiometricsAuthenticationCompletion"}],"navigatorTitle":[{"text":"TSNativeBiometricsAuthenticationCompletion","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSNativeBiometricsAuthenticationCompletion","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnError"}],"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnError"}],"type":"topic","abstract":[],"kind":"symbol","title":"TSWebAuthnError","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPRegistrationCompletion":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSTOTPRegistrationCompletion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSTOTPRegistrationCompletion"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tstotpregistrationcompletion","abstract":[],"title":"TSTOTPRegistrationCompletion","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPRegistrationCompletion"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSDeviceInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TSDeviceInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSDeviceInfo","kind":"symbol","title":"TSDeviceInfo","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSDeviceInfo"}],"url":"\/documentation\/tsauthenticationsdk\/tsdeviceinfo"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationCompletion":{"url":"\/documentation\/tsauthenticationsdk\/tsauthenticationcompletion","kind":"symbol","title":"TSAuthenticationCompletion","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationCompletion","navigatorTitle":[{"text":"TSAuthenticationCompletion","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAuthenticationCompletion","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPGenerateCodeCompletion":{"url":"\/documentation\/tsauthenticationsdk\/tstotpgeneratecodecompletion","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSTOTPGenerateCodeCompletion"}],"abstract":[],"kind":"symbol","title":"TSTOTPGenerateCodeCompletion","navigatorTitle":[{"kind":"identifier","text":"TSTOTPGenerateCodeCompletion"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPGenerateCodeCompletion"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSTOTPGenerateCodeResult":{"url":"\/documentation\/tsauthenticationsdk\/tstotpgeneratecoderesult","abstract":[],"role":"symbol","title":"TSTOTPGenerateCodeResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSTOTPGenerateCodeResult"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSTOTPGenerateCodeResult"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSTOTPGenerateCodeResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthentication"]},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationSDKVersionNumber","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationSDKVersionString"],"title":"Variables"}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/title","value":"TSAuthentication"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSAuthentication\/fragments","value":[{"text":"TSAuthentication","kind":"identifier"}],"op":"replace"}]}]}