{"metadata":{"roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentialRequestOptions"},{"text":": ","kind":"text"},{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"responseHeaders"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"externalID":"s:19TSAuthenticationSDK28TSWebAuthnAuthenticationDataV17webauthnSessionId24credentialRequestOptions15responseHeadersACSS_AA0cde10CredentialklF0CSDyS2SGSgtcfc","role":"symbol","modules":[{"name":"TSAuthenticationSDK"}],"title":"init(webauthnSessionId:credentialRequestOptions:responseHeaders:)"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData\/init(webauthnSessionId:credentialRequestOptions:responseHeaders:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData"]]},"abstract":[{"type":"text","text":"Manually initializes the "},{"type":"codeVoice","code":"TSWebAuthnAuthenticationData"},{"type":"text","text":" with explicit values."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata\/init(webauthnsessionid:credentialrequestoptions:responseheaders:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"webauthnSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentialRequestOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"responseHeaders"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"webauthnSessionId","content":[{"type":"paragraph","inlineContent":[{"text":"The optional session identifier for this authentication attempt.","type":"text"}]}]},{"name":"credentialRequestOptions","content":[{"type":"paragraph","inlineContent":[{"text":"The optional detailed options required for requesting an assertion.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional HTTP headers from the originating backend response. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"responseHeaders"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this initializer if you are constructing the authentication data programmatically"},{"type":"text","text":" "},{"type":"text","text":"rather than decoding it from JSON."}]}]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"role":"symbol","title":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata","type":"topic","navigatorTitle":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationData/init(webauthnSessionId:credentialRequestOptions:responseHeaders:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata\/init(webauthnsessionid:credentialrequestoptions:responseheaders:)","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Manually initializes the "},{"type":"codeVoice","code":"TSWebAuthnAuthenticationData"},{"text":" with explicit values.","type":"text"}],"title":"init(webauthnSessionId:credentialRequestOptions:responseHeaders:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData\/init(webauthnSessionId:credentialRequestOptions:responseHeaders:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webauthnSessionId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"credentialRequestOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"responseHeaders"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationData":{"kind":"symbol","abstract":[{"text":"Represents the data required to initiate a WebAuthn ","type":"text"},{"inlineContent":[{"text":"authentication","type":"text"}],"type":"strong"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TSWebAuthnAuthenticationData","kind":"identifier"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata","title":"TSWebAuthnAuthenticationData","navigatorTitle":[{"text":"TSWebAuthnAuthenticationData","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/title","value":"TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"value":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}