{"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webauthnSessionId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"credentialRequestOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"kind":"text","text":")"}],"modules":[{"name":"TSAuthenticationSDK"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","title":"init(webauthnSessionId:credentialRequestOptions:)","externalID":"s:19TSAuthenticationSDK28TSWebAuthnAuthenticationDataV17webauthnSessionId24credentialRequestOptionsACSS_AA0cde10CredentialklF0Ctcfc"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData\/init(webauthnSessionId:credentialRequestOptions:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"webauthnSessionId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"credentialRequestOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"webauthnSessionId","content":[{"inlineContent":[{"text":"The optional session identifier for this authentication attempt.","type":"text"}],"type":"paragraph"}]},{"name":"credentialRequestOptions","content":[{"inlineContent":[{"text":"The optional detailed options required for requesting an assertion.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this initializer if you are constructing the authentication data programmatically"},{"type":"text","text":" "},{"type":"text","text":"rather than decoding it from JSON."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata\/init(webauthnsessionid:credentialrequestoptions:)"]}],"abstract":[{"text":"Manually initializes the ","type":"text"},{"type":"codeVoice","code":"TSWebAuthnAuthenticationData"},{"type":"text","text":" with explicit values."}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationData":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData","title":"TSWebAuthnAuthenticationData","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticationData"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnAuthenticationData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata","abstract":[{"type":"text","text":"Represents the data required to initiate a WebAuthn "},{"type":"strong","inlineContent":[{"type":"text","text":"authentication"}]},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationData/init(webauthnSessionId:credentialRequestOptions:)":{"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webauthnSessionId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"credentialRequestOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"typeIdentifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Manually initializes the "},{"type":"codeVoice","code":"TSWebAuthnAuthenticationData"},{"type":"text","text":" with explicit values."}],"title":"init(webauthnSessionId:credentialRequestOptions:)","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationdata\/init(webauthnsessionid:credentialrequestoptions:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationData\/init(webauthnSessionId:credentialRequestOptions:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","role":"collection","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData":{"title":"TSWebAuthnAuthenticationCredentialRequestOptionsData","type":"topic","abstract":[],"navigatorTitle":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/title","value":"TSWebAuthnAuthenticationCredentialRequestOptionsData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}