{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData"]]},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/Encodable-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/encodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_dictionary"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_toDictionary(_:)"],"anchor":"Instance-Methods","generated":true}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Encodable Implementations","modules":[{"name":"TSAuthenticationSDK"}]},"kind":"article","sections":[],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/ts_toDictionary(_:)":{"title":"ts_toDictionary(_:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/ts_todictionary(_:)","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_toDictionary(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ts_toDictionary","kind":"identifier"},{"kind":"text","text":"("},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"kind":"text","text":") -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/ts_dictionary":{"title":"ts_dictionary","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_dictionary","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ts_dictionary","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/ts_dictionary","kind":"symbol","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"type":"topic","navigatorTitle":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"title":"TSWebAuthnPubKeyCredParamsData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","title":"TSAuthenticationSDK","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TSWebAuthnPubKeyCredParamsData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments","value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle"}]}]}