{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(from:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(from:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Decodable.init(from:)"},{"type":"text","text":"."}],"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"TSAuthenticationSDK"}],"externalID":"s:19TSAuthenticationSDK30TSWebAuthnPubKeyCredParamsDataC4fromACs7Decoder_p_tKcfc","roleHeading":"Initializer","symbolKind":"init","title":"init(from:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","title":"TSWebAuthnPubKeyCredParamsData","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"abstract":[],"navigatorTitle":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","title":"TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"init(from:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(from:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(from:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title","value":"TSWebAuthnPubKeyCredParamsData"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments","value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle"}]}]}