{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"alg"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol","externalID":"s:19TSAuthenticationSDK30TSWebAuthnPubKeyCredParamsDataC4type3algACSSSg_SiSgtcfc","symbolKind":"init","title":"init(type:alg:)","roleHeading":"Initializer"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"alg"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(type:alg:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(type:alg:)"},"kind":"symbol","references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","role":"collection","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/init(type:alg:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/init(type:alg:)","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/init(type:alg:)","abstract":[],"type":"topic","role":"symbol","title":"init(type:alg:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"alg"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"role":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","title":"TSWebAuthnPubKeyCredParamsData","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title","value":"TSWebAuthnPubKeyCredParamsData"},{"value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}