{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ts_toDictionary","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"encoder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder","kind":"typeIdentifier"},{"kind":"text","text":" = JSONEncoder()) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/ts_todictionary(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_toDictionary(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/Encodable-Implementations"]]},"metadata":{"role":"symbol","extendedModule":"Swift","title":"ts_toDictionary(_:)","roleHeading":"Instance Method","modules":[{"relatedModules":["Swift"],"name":"TSAuthenticationSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ts_toDictionary","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"symbolKind":"method","externalID":"s:SE9TSCoreSDKE15ts_toDictionaryySDySSypGSg10Foundation11JSONEncoderCF::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.ts_toDictionary(_:)"},{"text":".","type":"text"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/Encodable-Implementations":{"title":"Encodable Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/encodable-implementations","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/Encodable-Implementations"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"navigatorTitle":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","title":"TSWebAuthnPubKeyCredParamsData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData/ts_toDictionary(_:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata\/ts_todictionary(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData\/ts_toDictionary(_:)","kind":"symbol","title":"ts_toDictionary(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"TSWebAuthnPubKeyCredParamsData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments"},{"op":"replace","value":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}