{"metadata":{"roleHeading":"API Collection","modules":[{"name":"TSAuthenticationSDK"}],"title":"Encodable Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/encodable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData"]]},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/Encodable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_dictionary"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_toDictionary(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"kind":"article","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/ts_dictionary":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"type":"topic","kind":"symbol","title":"ts_dictionary","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_dictionary","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/ts_dictionary"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","navigatorTitle":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","title":"TSWebAuthnAuthenticatorSelectionData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/ts_toDictionary(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC","text":"JSONEncoder"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"type":"topic","kind":"symbol","title":"ts_toDictionary(_:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_toDictionary(_:)","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/ts_todictionary(_:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","title":"TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"}},"variantOverrides":[{"patch":[{"value":"TSWebAuthnAuthenticatorSelectionData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}]},{"value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}