{"metadata":{"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"TSAuthenticationSDK"}],"title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","externalID":"s:19TSAuthenticationSDK36TSWebAuthnAuthenticatorSelectionDataC4fromACs7Decoder_p_tKcfc"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(from:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]}]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/init(from:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(from:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","role":"collection"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","kind":"symbol","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","title":"TSWebAuthnAuthenticatorSelectionData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSWebAuthnAuthenticatorSelectionData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"op":"replace"},{"op":"replace","value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}