{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"authenticatorAttachment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"requireResidentKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"? = nil, ","kind":"text"},{"text":"userVerification","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData"]]},"metadata":{"roleHeading":"Initializer","title":"init(authenticatorAttachment:requireResidentKey:userVerification:)","symbolKind":"init","externalID":"s:19TSAuthenticationSDK36TSWebAuthnAuthenticatorSelectionDataC23authenticatorAttachment18requireResidentKey16userVerificationACSSSg_SbSgAGtcfc","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"authenticatorAttachment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"requireResidentKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":"?, ","kind":"text"},{"text":"userVerification","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"modules":[{"name":"TSAuthenticationSDK"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(authenticatorattachment:requireresidentkey:userverification:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(authenticatorAttachment:requireResidentKey:userVerification:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","kind":"symbol","title":"TSAuthenticationSDK","role":"collection","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/init(authenticatorAttachment:requireResidentKey:userVerification:)":{"abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/init(authenticatorattachment:requireresidentkey:userverification:)","title":"init(authenticatorAttachment:requireResidentKey:userVerification:)","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/init(authenticatorAttachment:requireResidentKey:userVerification:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"authenticatorAttachment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"requireResidentKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"text":"userVerification","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"type":"topic","role":"symbol","kind":"symbol","title":"TSWebAuthnAuthenticatorSelectionData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title","value":"TSWebAuthnAuthenticatorSelectionData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments","value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle"}]}]}