{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.ts_dictionary"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_dictionary"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/Encodable-Implementations"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/ts_dictionary"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"ts_dictionary","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_dictionary"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:SE9TSCoreSDKE13ts_dictionarySDySSypGSgvp::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData","extendedModule":"Swift","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"TSAuthenticationSDK"}]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/ts_dictionary":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/ts_dictionary","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/ts_dictionary","title":"ts_dictionary"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"title":"TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","role":"collection","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData/Encodable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData\/Encodable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata\/encodable-implementations","type":"topic","title":"Encodable Implementations"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"TSWebAuthnAuthenticatorSelectionData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"navigatorTitle":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title","op":"replace","value":"TSWebAuthnAuthenticatorSelectionData"},{"value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle","value":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"op":"replace"}]}]}