{"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_dictionary"]},{"identifiers":["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_toDictionary(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/Encodable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/encodable-implementations"]}],"metadata":{"title":"Encodable Implementations","modules":[{"name":"TSAuthenticationSDK"}],"role":"collectionGroup","roleHeading":"API Collection"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData":{"abstract":[],"kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","title":"TSWebAuthnAuthenticationCredentialRequestOptionsData","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData/ts_dictionary":{"abstract":[],"title":"ts_dictionary","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_dictionary","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/ts_dictionary","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData/ts_toDictionary(_:)":{"abstract":[],"title":"ts_toDictionary(_:)","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/ts_todictionary(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_toDictionary"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSONEncoder","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_toDictionary(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/title","value":"TSWebAuthnAuthenticationCredentialRequestOptionsData"},{"value":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}