{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"challenge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"allowCredentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData","text":"TSWebAuthnAllowCredentialsData"},{"kind":"text","text":"]? = nil, "},{"text":"userVerification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"rpId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","text":"TSWebAuthnUserData"},{"kind":"text","text":"? = nil)"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","modules":[{"name":"TSAuthenticationSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"challenge"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"allowCredentials","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"userVerification"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rpId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","text":"TSWebAuthnUserData","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:19TSAuthenticationSDK52TSWebAuthnAuthenticationCredentialRequestOptionsDataC9challenge16allowCredentials16userVerification4rpId0M0ACSSSg_SayAA0cd5AllowlI0CGSgA2iA0cd4UserI0CSgtcfc","title":"init(challenge:allowCredentials:userVerification:rpId:user:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/init(challenge:allowcredentials:userverification:rpid:user:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/init(challenge:allowCredentials:userVerification:rpId:user:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData":{"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","type":"topic","navigatorTitle":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata","title":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAllowCredentialsData":{"abstract":[],"role":"symbol","kind":"symbol","title":"TSWebAuthnAllowCredentialsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnallowcredentialsdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"navigatorTitle":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAllowCredentialsData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData/init(challenge:allowCredentials:userVerification:rpId:user:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"challenge","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowCredentials"},{"text":": [","kind":"text"},{"text":"TSWebAuthnAllowCredentialsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAllowCredentialsData"},{"kind":"text","text":"]?, "},{"text":"userVerification","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"rpId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"text":"TSWebAuthnUserData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData"},{"kind":"text","text":"?)"}],"abstract":[],"title":"init(challenge:allowCredentials:userVerification:rpId:user:)","type":"topic","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/init(challenge:allowcredentials:userverification:rpid:user:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/init(challenge:allowCredentials:userVerification:rpId:user:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","title":"TSAuthenticationSDK","kind":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData":{"title":"TSWebAuthnUserData","role":"symbol","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata","navigatorTitle":[{"text":"TSWebAuthnUserData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSWebAuthnUserData","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSWebAuthnAuthenticationCredentialRequestOptionsData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/title","value":"TSWebAuthnAllowCredentialsData","op":"replace"},{"value":[{"text":"TSWebAuthnAllowCredentialsData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnAllowCredentialsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAllowCredentialsData\/navigatorTitle"},{"value":"TSWebAuthnUserData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TSWebAuthnUserData"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/fragments"},{"value":[{"kind":"identifier","text":"TSWebAuthnUserData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}