{"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/ts_dictionary"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_dictionary"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Encodable.ts_dictionary","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ts_dictionary","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"ts_dictionary","externalID":"s:SE9TSCoreSDKE13ts_dictionarySDySSypGSgvp::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticationCredentialRequestOptionsData","extendedModule":"Swift","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"TSAuthenticationSDK","relatedModules":["Swift"]}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_dictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/Encodable-Implementations"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"title":"TSAuthenticationSDK","type":"topic","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData/ts_dictionary":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"kind":"symbol","abstract":[],"title":"ts_dictionary","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/ts_dictionary","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/ts_dictionary"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData/Encodable-Implementations":{"kind":"article","title":"Encodable Implementations","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata\/encodable-implementations","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData\/Encodable-Implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticationCredentialRequestOptionsData":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticationCredentialRequestOptionsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticationcredentialrequestoptionsdata","title":"TSWebAuthnAuthenticationCredentialRequestOptionsData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TSWebAuthnAuthenticationCredentialRequestOptionsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/title"},{"value":[{"text":"TSWebAuthnAuthenticationCredentialRequestOptionsData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticationCredentialRequestOptionsData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticationCredentialRequestOptionsData"}],"op":"replace"}]}]}