{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData"]]},"abstract":[{"type":"text","text":"Manually initializes the "},{"type":"codeVoice","code":"TSWebAuthnRegistrationData"},{"text":" with explicit values.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata\/init(webauthnsessionid:credentialcreationoptions:responseheaders:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData\/init(webauthnSessionId:credentialCreationOptions:responseHeaders:)"},"metadata":{"title":"init(webauthnSessionId:credentialCreationOptions:responseHeaders:)","externalID":"s:19TSAuthenticationSDK26TSWebAuthnRegistrationDataV17webauthnSessionId25credentialCreationOptions15responseHeadersACSS_AA0cd17CredentialRequestlF0CSDyS2SGSgtcfc","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"credentialCreationOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSWebAuthnCredentialRequestOptionsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData"},{"kind":"text","text":", "},{"text":"responseHeaders","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}],"modules":[{"name":"TSAuthenticationSDK"}],"symbolKind":"init","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"credentialCreationOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSWebAuthnCredentialRequestOptionsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData","kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"responseHeaders"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The session identifier for this registration attempt."}],"type":"paragraph"}],"name":"webauthnSessionId"},{"name":"credentialCreationOptions","content":[{"inlineContent":[{"text":"The detailed options required for credential creation.","type":"text"}],"type":"paragraph"}]},{"name":"responseHeaders","content":[{"inlineContent":[{"text":"Optional HTTP headers from the originating backend response. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this initializer if you are constructing the registration data programmatically"},{"type":"text","text":" "},{"text":"rather than decoding it from JSON.","type":"text"}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRegistrationData":{"navigatorTitle":[{"text":"TSWebAuthnRegistrationData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData","abstract":[{"type":"text","text":"Represents the data required to initiate a WebAuthn "},{"type":"strong","inlineContent":[{"type":"text","text":"registration"}]},{"text":" .","type":"text"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSWebAuthnRegistrationData","kind":"identifier"}],"role":"symbol","title":"TSWebAuthnRegistrationData","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRegistrationData/init(webauthnSessionId:credentialCreationOptions:responseHeaders:)":{"type":"topic","abstract":[{"type":"text","text":"Manually initializes the "},{"type":"codeVoice","code":"TSWebAuthnRegistrationData"},{"type":"text","text":" with explicit values."}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData\/init(webauthnSessionId:credentialCreationOptions:responseHeaders:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentialCreationOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData","kind":"typeIdentifier","text":"TSWebAuthnCredentialRequestOptionsData"},{"text":", ","kind":"text"},{"text":"responseHeaders","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(webauthnSessionId:credentialCreationOptions:responseHeaders:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata\/init(webauthnsessionid:credentialcreationoptions:responseheaders:)","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"role":"symbol","title":"TSWebAuthnCredentialRequestOptionsData","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title","op":"replace","value":"TSWebAuthnCredentialRequestOptionsData"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}]}]}]}