{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"credentialCreationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSWebAuthnCredentialRequestOptionsData","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"webauthnSessionId","content":[{"inlineContent":[{"text":"The session identifier for this registration attempt.","type":"text"}],"type":"paragraph"}]},{"name":"credentialCreationOptions","content":[{"type":"paragraph","inlineContent":[{"text":"The detailed options required for credential creation.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Use this initializer if you are constructing the registration data programmatically","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"rather than decoding it from JSON."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:19TSAuthenticationSDK26TSWebAuthnRegistrationDataV17webauthnSessionId25credentialCreationOptionsACSS_AA0cd17CredentialRequestlF0Ctcfc","roleHeading":"Initializer","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webauthnSessionId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"credentialCreationOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData"},{"text":")","kind":"text"}],"title":"init(webauthnSessionId:credentialCreationOptions:)","modules":[{"name":"TSAuthenticationSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata\/init(webauthnsessionid:credentialcreationoptions:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData"]]},"abstract":[{"text":"Manually initializes the ","type":"text"},{"code":"TSWebAuthnRegistrationData","type":"codeVoice"},{"text":" with explicit values.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData\/init(webauthnSessionId:credentialCreationOptions:)"},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"title":"TSAuthenticationSDK","type":"topic","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRegistrationData/init(webauthnSessionId:credentialCreationOptions:)":{"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData\/init(webauthnSessionId:credentialCreationOptions:)","abstract":[{"type":"text","text":"Manually initializes the "},{"code":"TSWebAuthnRegistrationData","type":"codeVoice"},{"text":" with explicit values.","type":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata\/init(webauthnsessionid:credentialcreationoptions:)","role":"symbol","title":"init(webauthnSessionId:credentialCreationOptions:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"webauthnSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"credentialCreationOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData"},{"kind":"text","text":")"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRegistrationData":{"navigatorTitle":[{"text":"TSWebAuthnRegistrationData","kind":"identifier"}],"abstract":[{"text":"Represents the data required to initiate a WebAuthn ","type":"text"},{"inlineContent":[{"type":"text","text":"registration"}],"type":"strong"},{"type":"text","text":" ."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnRegistrationData","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnregistrationdata","title":"TSWebAuthnRegistrationData","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRegistrationData","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","title":"TSWebAuthnCredentialRequestOptionsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title","value":"TSWebAuthnCredentialRequestOptionsData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}]},{"value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}