{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"challenge"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"pubKeyCredParams","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData","text":"TSWebAuthnPubKeyCredParamsData","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData"},{"kind":"text","text":"]? = nil, "},{"text":"attestation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"excludeCredentials"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"text":"authenticatorSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData","text":"TSWebAuthnAuthenticatorSelectionData"},{"text":"? = nil, ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSWebAuthnUserData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData"},{"kind":"text","text":"? = nil, "},{"text":"rp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData","text":"TSWebAuthnRPData","kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pubKeyCredParams"},{"kind":"text","text":": ["},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"attestation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"excludeCredentials","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"authenticatorSelection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSWebAuthnAuthenticatorSelectionData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timeout"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","text":"TSWebAuthnUserData","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rp","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSWebAuthnRPData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"TSAuthenticationSDK"}],"externalID":"s:19TSAuthenticationSDK38TSWebAuthnCredentialRequestOptionsDataC9challenge16pubKeyCredParams11attestation18excludeCredentials22authenticatorSelection7timeout4user2rpACSSSg_SayAA0cd3PubklmH0CGSgALSaySSGSgAA0cd13AuthenticatorrH0CSgSiSgAA0cd4UserH0CSgAA0cD6RPDataCtcfc","title":"init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/init(challenge:pubkeycredparams:attestation:excludecredentials:authenticatorselection:timeout:user:rp:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pubKeyCredParams"},{"kind":"text","text":": ["},{"text":"TSWebAuthnPubKeyCredParamsData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnPubKeyCredParamsData","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"attestation"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"excludeCredentials","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"authenticatorSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnAuthenticatorSelectionData"},{"text":"?, ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSWebAuthnUserData","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnUserData","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"rp","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TSWebAuthnRPData","kind":"typeIdentifier","preciseIdentifier":"c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnRPData"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","title":"init(challenge:pubKeyCredParams:attestation:excludeCredentials:authenticatorSelection:timeout:user:rp:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/init(challenge:pubkeycredparams:attestation:excludecredentials:authenticatorselection:timeout:user:rp:)"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnUserData":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnUserData"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSWebAuthnUserData"}],"title":"TSWebAuthnUserData","type":"topic","abstract":[],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnuserdata","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnUserData"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnRPData":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnrpdata","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnRPData"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnRPData","title":"TSWebAuthnRPData","navigatorTitle":[{"text":"TSWebAuthnRPData","kind":"identifier"}],"role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnPubKeyCredParamsData":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnPubKeyCredParamsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnpubkeycredparamsdata","kind":"symbol","title":"TSWebAuthnPubKeyCredParamsData","type":"topic","role":"symbol","navigatorTitle":[{"text":"TSWebAuthnPubKeyCredParamsData","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"role":"symbol","title":"TSWebAuthnCredentialRequestOptionsData","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnAuthenticatorSelectionData":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}],"title":"TSWebAuthnAuthenticatorSelectionData","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnAuthenticatorSelectionData","url":"\/documentation\/tsauthenticationsdk\/tswebauthnauthenticatorselectiondata","type":"topic","navigatorTitle":[{"text":"TSWebAuthnAuthenticatorSelectionData","kind":"identifier"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/title","value":"TSWebAuthnUserData"},{"value":[{"text":"TSWebAuthnUserData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnUserData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnUserData"}],"op":"replace"},{"op":"replace","value":"TSWebAuthnRPData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/title"},{"value":[{"text":"TSWebAuthnRPData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnRPData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnRPData\/navigatorTitle"},{"value":"TSWebAuthnPubKeyCredParamsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TSWebAuthnPubKeyCredParamsData"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnPubKeyCredParamsData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title","value":"TSWebAuthnCredentialRequestOptionsData","op":"replace"},{"op":"replace","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle"},{"value":"TSWebAuthnAuthenticatorSelectionData","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnAuthenticatorSelectionData\/navigatorTitle","value":[{"kind":"identifier","text":"TSWebAuthnAuthenticatorSelectionData"}],"op":"replace"}]}]}