{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/ts_dictionary"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Encodable.ts_dictionary","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/ts_dictionary"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations"]]},"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_dictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"modules":[{"name":"TSAuthenticationSDK","relatedModules":["Swift"]}],"roleHeading":"Instance Property","title":"ts_dictionary","extendedModule":"Swift","externalID":"s:SE9TSCoreSDKE13ts_dictionarySDySSypGSgvp::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_dictionary"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/Encodable-Implementations":{"kind":"article","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations","type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/encodable-implementations","abstract":[],"title":"Encodable Implementations","role":"collectionGroup"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"title":"TSWebAuthnCredentialRequestOptionsData","kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","title":"TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/ts_dictionary":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/ts_dictionary","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ts_dictionary","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"title":"ts_dictionary","abstract":[],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/ts_dictionary","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TSWebAuthnCredentialRequestOptionsData","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title"},{"value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle"}]}]}