{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"encoder"},{"text":": ","kind":"text"},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"text":" = JSONEncoder()) -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Encodable.ts_toDictionary(_:)","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","extendedModule":"Swift","externalID":"s:SE9TSCoreSDKE15ts_toDictionaryySDySSypGSg10Foundation11JSONEncoderCF::SYNTHESIZED::c:@M@TSAuthenticationSDK@objc(cs)TSWebAuthnCredentialRequestOptionsData","title":"ts_toDictionary(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"text":"JSONEncoder","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11JSONEncoderC"},{"kind":"text","text":") -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"role":"symbol","modules":[{"name":"TSAuthenticationSDK","relatedModules":["Swift"]}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/ts_todictionary(_:)"]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/ts_toDictionary(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/ts_toDictionary(_:)":{"role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/ts_todictionary(_:)","title":"ts_toDictionary(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ts_toDictionary"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation11JSONEncoderC","kind":"typeIdentifier","text":"JSONEncoder"},{"text":") -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/ts_toDictionary(_:)","abstract":[],"kind":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData/Encodable-Implementations":{"title":"Encodable Implementations","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData\/Encodable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata\/encodable-implementations","abstract":[],"kind":"article"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"title":"TSAuthenticationSDK","type":"topic","url":"\/documentation\/tsauthenticationsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnCredentialRequestOptionsData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnCredentialRequestOptionsData","title":"TSWebAuthnCredentialRequestOptionsData","url":"\/documentation\/tsauthenticationsdk\/tswebauthncredentialrequestoptionsdata","navigatorTitle":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/title","value":"TSWebAuthnCredentialRequestOptionsData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/fragments","value":[{"kind":"identifier","text":"TSWebAuthnCredentialRequestOptionsData"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSAuthenticationSDK~1documentation~1TSAuthenticationSDK~1TSWebAuthnCredentialRequestOptionsData\/navigatorTitle","value":[{"text":"TSWebAuthnCredentialRequestOptionsData","kind":"identifier"}],"op":"replace"}]}]}